# Generated by Django 5.2.3 on 2025-06-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Aéroport',
                'verbose_name_plural': 'Aéroports',
                'db_table': 'aeroport',
            },
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('pays_rattachement', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Compagnie',
                'verbose_name_plural': 'Compagnies',
                'db_table': 'compagnie',
            },
        ),
        migrations.CreateModel(
            name='TypeAvion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('longueur_piste_necessaire', models.IntegerField()),
            ],
            options={
                'verbose_name': "Type d'Avion",
                'verbose_name_plural': "Types d'Avion",
                'db_table': 'type_avion',
            },
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avions', to='gestion_trafic_aerien.compagnie')),
                ('type_avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avions', to='gestion_trafic_aerien.typeavion')),
            ],
            options={
                'verbose_name': 'Avion',
                'verbose_name_plural': 'Avions',
                'db_table': 'avion',
            },
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilote', models.CharField(max_length=100)),
                ('date_heure_depart', models.DateTimeField()),
                ('date_heure_arrivee', models.DateTimeField()),
                ('aeroport_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_arrivee', to='gestion_trafic_aerien.aeroport')),
                ('aeroport_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_depart', to='gestion_trafic_aerien.aeroport')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols', to='gestion_trafic_aerien.avion')),
            ],
            options={
                'verbose_name': 'Vol',
                'verbose_name_plural': 'Vols',
                'db_table': 'vol',
                'ordering': ['date_heure_depart'],
            },
        ),
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('longueur', models.IntegerField()),
                ('aeroport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistes', to='gestion_trafic_aerien.aeroport')),
            ],
            options={
                'verbose_name': 'Piste',
                'verbose_name_plural': 'Pistes',
                'db_table': 'piste',
                'unique_together': {('numero', 'aeroport')},
            },
        ),
    ]
